/*
This SQL file is intended for use with PostgreSQL and DB2. 
*/

/*
Ron Penones | July 10th 2025 - Feel free to share and reproduce, the core idea is mine with some assistance of AI. Padayon!
*/

create table megaplanet.customers_potential (meg_id INT generated always as identity primary key,
meg_first_name VARCHAR(50) not null,
meg_last_name VARCHAR(50) not null,
meg_mail VARCHAR(100) not null,
meg_phone VARCHAR(20) not null,
meg_bir_tin_principal VARCHAR(20) not null,
meg_bir_tin_married VARCHAR(20) not null,
created_at TIMESTAMP default CURRENT_TIMESTAMP not null,
updated_at TIMESTAMP default CURRENT_TIMESTAMP not null);

CREATE TABLE megaplanet.CUSTOMERS_MOBILE (
  MEG_ID VARCHAR (5),
  MEG_FIRST_NAME VARCHAR(50) NOT NULL,
  MEG_LAST_NAME VARCHAR(50) NOT NULL,
  MEG_PHONE VARCHAR(20) NOT NULL,
  MEG_PHONE_LEGITIMACY SMALLINT CHECK (MEG_PHONE_LEGITIMACY IN (0,1))
);

ALTER TABLE megaplanet.CUSTOMERS_MOBILE
ALTER COLUMN MEG_PHONE_LEGITIMACY SET DEFAULT 1;

CREATE TABLE megaplanet.CUSTOMERS_TAX (
  MEG_ID VARCHAR (5),
  MEG_FIRST_NAME VARCHAR(50) NOT NULL,
  MEG_LAST_NAME VARCHAR(50) NOT NULL,
  MEG_BIR_TIN_PRINCIPAL VARCHAR(20) NOT NULL,
  MEG_BIR_TIN_MARRIED VARCHAR(20) NOT NULL,
  MEG_BIR_TIN_PRINCIPAL__GROSS_PHP_ELIGIBLE SMALLINT CHECK (MEG_BIR_TIN_PRINCIPAL__GROSS_PHP_ELIGIBLE IN (0,1)),
  MEG_BIR_TIN_MARRIED__GROSS_PHP_ELIGIBLE SMALLINT CHECK (MEG_BIR_TIN_MARRIED__GROSS_PHP_ELIGIBLE IN (0,1))
);

ALTER TABLE megaplanet.CUSTOMERS_TAX
ALTER COLUMN MEG_BIR_TIN_PRINCIPAL__GROSS_PHP_ELIGIBLE SET DEFAULT 1;

ALTER TABLE megaplanet.CUSTOMERS_TAX
ALTER COLUMN MEG_BIR_TIN_MARRIED__GROSS_PHP_ELIGIBLE SET DEFAULT 1;

CREATE TABLE megaplanet.CUSTOMERS_FINANCIAL_CRIME (
  MEG_ID VARCHAR (5),
  MEG_FIRST_NAME VARCHAR(50) NOT NULL,
  MEG_LAST_NAME VARCHAR(50) NOT NULL,
  MEG_FIN_PRINCIPAL_CRIME_CLEAR SMALLINT CHECK (MEG_FIN_PRINCIPAL_CRIME_CLEAR IN (0,1)),
  MEG_FIN_MARRIED_CRIME_CLEAR SMALLINT CHECK (MEG_FIN_MARRIED_CRIME_CLEAR IN (0,1))
);

ALTER TABLE megaplanet.CUSTOMERS_FINANCIAL_CRIME
ALTER COLUMN MEG_FIN_PRINCIPAL_CRIME_CLEAR SET DEFAULT 1;

ALTER TABLE megaplanet.CUSTOMERS_FINANCIAL_CRIME
ALTER COLUMN MEG_FIN_MARRIED_CRIME_CLEAR SET DEFAULT 1;

CREATE TABLE megaplanet.CUSTOMERS_POTENTIAL_SEMI_SHORTLISTED (
  MEG_ID VARCHAR (5),
  MEG_FIRST_NAME VARCHAR(50),
  MEG_LAST_NAME VARCHAR(50),
  MEG_PHONE VARCHAR (20),
  MEG_PHONE_LEGITIMACY VARCHAR (1),
 MEG_FINANCIAL_GROSS_ELIGIBLE VARCHAR (1),
MEG_FINANCIAL_CRIME_CLEARED VARCHAR (1)
);

CREATE TABLE megaplanet.CUSTOMERS_POTENTIAL_REJECTED (
  MEG_ID VARCHAR (5),
  MEG_FIRST_NAME VARCHAR(50),
  MEG_LAST_NAME VARCHAR(50)
);


CREATE TABLE megaplanet.CUSTOMERS_POTENTIAL_PRE_APPROVED (
  MEG_ID VARCHAR (5),
  MEG_FIRST_NAME VARCHAR(50),
  MEG_LAST_NAME VARCHAR(50)
);